name: flutter_project
description: A simple Flutter app with login and signup pages.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_secure_storage: ^8.0.0
  flutter_local_notifications: ^18.0.1
  cupertino_icons: ^1.0.8
  agora_rtc_engine: ^6.5.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.4.0
  image_picker: ^1.1.2
  lottie: ^2.6.0
  timeago: ^3.3.0

  # firebase_auth: ^4.0.0
 

 
  # Add any dependencies here
  # e.g., firebase_auth for Firebase authentication, provider for state management

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Add any assets here if you want to use images, etc.
 